# Generated by Django 4.1 on 2022-08-15 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('birth_date', models.DateField(null=True)),
                ('designation', models.CharField(choices=[('ASE', 'Associate Software Engineer'), ('LSE', 'Lead Software Engineer'), ('CTO', 'Chief Technical Officer')], default='ASE', max_length=3)),
                ('software_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='api.softwarehouse')),
            ],
        ),
    ]
